### PR TITLE
Add device_system.cmake file for MIMXRT685 and MIMXRT595

### PR DESCRIPTION
**Pull request by mmahadevan108**
**Prerequisites**
- [X] I have checked latest main branch and the issue still exists.
- [X] I did not see it is stated as known-issue in release notes.
- [X] No similar GitHub issue is related to this change.
- [X] My code follows the commit guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**
On the MIMXRT685, spilt this out of device_startup.cmake to be consistent with other platforms.
Add device_system.cmake file for MIMXRT595

Fixes # (issue)

**Type of change** (please delete options that are not relevant):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**

* Test configuration (please complete the following information):
   - Hardware setting:
   - Toolchain:
   - Test Tool preparation:
   - Any other dependencies:
* Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
    - [X] Build Test
    - [ ] Run Test

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@mcuxsusan @dleach02 . We would like to start adding `system_xxxx.c` files in Zephyr. Hence this fix is needed so this file can be pulled in.

**Comment by mcuxsusan** [comment]
Hi @mmahadevan108, thanks for your contribution!

This misalignment of cmake component for RT595S and RT685S is because of the component data organization is different from others.
I agree with your change to add a new device_system component because up layer stack needs system sources for device enablement, but currently I would suggest we do not modify the existing device_startup component in this PR because now only device_startup component is included for examples on RT685S and RT595S, so merging this PR may introduce build failure for our existing examples.

So, please update PR to only add the device_system cmake component, I will do update later on updating device_startup component and the include components for examples in our RT685S and RT595S.

**Comment by mmahadevan108** [comment]
@mcuxsusan , thank you for your review. I have update this PR.

**Review by mcuxsusan — APPROVED** [review]
The change is OK for me, thanks.

**Pull request merged**
